### ISSUE TITLE
Add new Xtext editor quickfixes on *.xtext files

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext-eclipse#1448] opened 2020-05-12 10:12 UTC
The Xtext editor should provide the following quickfixes on `*.xtext` files:

- Provide quickfixes for illegal rule references (see [#331943](https://bugs.eclipse.org/bugs/show_bug.cgi?id=331943)) 
- Provide quickfixes for illegal hidden token definitions (see [#331942](https://bugs.eclipse.org/bugs/show_bug.cgi?id=331942))
- Provide more quickfixes for missing rules (see [#331941](https://bugs.eclipse.org/bugs/show_bug.cgi?id=331941))

@loradd Would you like to take care of this issue?

**Comment by nbhusare** [comment] 2020-05-27 15:03
@miklossy I would like to work on this issue. Kindly let me know if that is ok.

**Comment by miklossy** [comment] 2020-05-27 15:31
@nbhusare Would be awesome if you could take care of this issue. Thanks a lot in advance!

**Comment by loradd** [comment] 2020-05-28 14:04
@miklossy sorry for the late reply! 
I could also work on this, @nbhusare let me know if you need support.

**Comment by miklossy** [comment] 2020-05-28 14:23
Thanks for your reply @loradd . I would sugges that @nbhusare will take care of this issue, for you @loradd I created a similar one to the Xtend repository: https://github.com/eclipse/xtext-xtend/issues/1060 . Please comment on that issue if you could take care of that one. Thanks!

**Comment by nbhusare** [comment] 2020-07-01 19:33
@szarnekow - The method `XtextGrammarQuickfixProvider.fixUnresolvedRule(Issue, IssueResolutionAcceptor)`, on [line 144](https://github.com/eclipse/xtext-eclipse/blob/master/org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/editor/quickfix/XtextGrammarQuickfixProvider.java#L144), specifically gets a container of type `ParserRule`. Yet, on [line 149](https://github.com/eclipse/xtext-eclipse/blob/master/org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/editor/quickfix/XtextGrammarQuickfixProvider.java#L149), it checks if the `if (abstractRule instanceof TerminalRule)`. I looked at the history (PS comment below) and I don't understand it. Could you please confirm if this code is required?

Comment from history - Use textual modification instead of semantic modification for new parser rules as serialization / comment location preserving is to fragile for invalid models

**Comment by szarnekow** [comment] 2020-07-03 09:43
> @szarnekow - The method `XtextGrammarQuickfixProvider.fixUnresolvedRule(Issue, IssueResolutionAcceptor)`, on [line 144](https://github.com/eclipse/xtext-eclipse/blob/master/org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/editor/quickfix/XtextGrammarQuickfixProvider.java#L144), specifically gets a container of type `ParserRule`. Yet, on [line 149](https://github.com/eclipse/xtext-eclipse/blob/master/org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/editor/quickfix/XtextGrammarQuickfixProvider.java#L149), it checks if the `if (abstractRule instanceof TerminalRule)`. I looked at the history (PS comment below) and I don't understand it. Could you please confirm if the code on line 149 is required?

It's a bug. It should probably get a container of type AbstractRule in line 144.

**Comment by nbhusare** [comment] 2020-07-06 13:17
@szarnekow I have replaced the existing PR's with new ones. I have addressed the review comments in the same. Kindly have a look.

**Comment by nbhusare** [comment] 2020-07-19 06:40
@miklossy We have merged the PR's. Could you please close this issue. Tx

**Comment by miklossy** [comment] 2020-07-19 06:45
Thanks for your contibution @nbhusare ! I would like to try  out the new quickfixes before closing this issue.

**Comment by miklossy** [comment] 2020-07-20 05:09
@nbhusare  I took a look at the current state of the fix and found the following shortcomings:

- In some cases, the `Convert terminal fragment to terminal rule` quickfix is offered but has no effect:
![screencast](https://user-images.githubusercontent.com/20393472/87901365-1fa39080-ca57-11ea-8519-1ff8a8b9361a.gif)

- Did you fix the bug [#331941](https://bugs.eclipse.org/bugs/show_bug.cgi?id=331941) completely? E.g. the `Create terminal rule ` quickfix is not offered where it should be:
![screenshot](https://user-images.githubusercontent.com/20393472/87901339-14506500-ca57-11ea-8eef-8387edc096ac.png)

- Would be awesome if you could add some words about this fix to the release notes, see https://github.com/eclipse/xtext/issues/1786

**Comment by nbhusare** [comment] 2020-07-21 06:34
@miklossy Let me take a look at the above.

**Comment by nbhusare** [comment] 2020-07-21 09:41
@miklossy I have raised a PR ([xtext-eclipse/pull/1492](https://github.com/eclipse/xtext-eclipse/pull/1492)) to address the first issue you reported above. For the second one, to show the two quick-fixes proposals (Create terminal..., Create terminal fragment...), I added the annotation `@Fix(XtextLinkingDiagnosticMessageProvider.UNRESOLVED_RULE)` on the methods `fixUnresolvedTerminalRule()`, and `fixUnresolvedTerminalFragmentRule()`, and also enhanced the method `createNewRule()`; however, it adds multiple of "Change to 'XXX'" proposal in addition to the required ones. Is there a way to only show one "Change to 'XXX'" proposal?

![image](https://user-images.githubusercontent.com/3328139/88038802-5b784c00-cb64-11ea-832e-70fb6a495943.png)

**Comment by cdietrich** [comment] 2020-07-21 10:03
@nbhusare why are there 3 quickfixed created at all?
how to reproduce this?

**Comment by miklossy** [comment] 2020-07-21 10:14
Thanks @cdietrich for jumping in and taking over!

**Comment by nbhusare** [comment] 2020-07-21 10:36
@cdietrich Sorry, by 3 quick-fixes do you mean the "Change to 'PQR'" ones, or the Create XX ones?
To reproduce the issue, please add annotation `@Fix(XtextLinkingDiagnosticMessageProvider.UNRESOLVED_RULE)` to the methods `fixUnresolvedTerminalRule()`, and `fixUnresolvedTerminalFragmentRule()` in `XtextGrammarQuickFixProvider`. Please use `Model: a=ID2` grammar as an example.

**Comment by cdietrich** [comment] 2020-07-21 10:40
if you call createLinkingIssueResolutions three times and dont filter the typo fixes then of course you get 3 fixes

**Comment by nbhusare** [comment] 2020-07-21 10:48
@cdietrich Tx for the tip. Let me take a look.

**Comment by nbhusare** [comment] 2020-07-24 13:18
@cdietrich @szarnekow I came across the following issues while working on this task. Please have a look.
Also filed jiras - https://bugs.eclipse.org/bugs/show_bug.cgi?id=565523, https://bugs.eclipse.org/bugs/show_bug.cgi?id=565524 respectively. 

1. In the grammar below, the quick-fix "Remove Hidden token definition" fails with the following error. The serializer fails in serializing the broken reference `name=IDX`
```
Model hidden(ModelA):  // Reference to a parser-rule
    name=IDX; //IDX is not defined yet
ModelA:
    name=ID;
```
```
java.lang.RuntimeException: Could not serialize RuleCall:
RuleCall.rule is required to have a value, but it does not.
Semantic Object: Grammar'org.xtext.example.mydsl.MyDsl'.rules[0]->ParserRule'Model'.alternatives->Assignment.terminal->RuleCall
URI: platform:/resource/org.xtext.example.mydsl/src/org/xtext/example/mydsl/MyDsl.xtext
Context: AssignableTerminal returns RuleCall
```

2. In the below grammar, for the hidden token A, I get three proposals - Change to B, Convert terminal fragment to terminal rule, and Remove hidden token definition. In the method `XtextValidator#checkHiddenTokenIsNotAFragment()`, the **number** of hidden tokens returned is one, even though we have two tokens defined (one has a broken reference). The index value that is passed to the call to `addIssue()` is 0, and as a side-effect, we see three proposals for the hidden token definition. In short, the proposals shown (at least the second and the third) applicable to the hidden token `B` are displayed for the token `A`. 

Now, if I choose the proposal "Remove hidden token definition", all the tokens get removed. Proposal "Change to B" works, but it doesn't make sense since B is a terminal fragment. "Convert terminal Fragment to terminal rule" does not make sense either.
```
Model hidden(A, B):
	name=ID;
terminal fragment B:
	'b';
```

**Comment by cdietrich** [comment] 2020-08-03 08:45
ping @szarnekow

**Comment by nbhusare** [comment] 2020-08-10 14:23
> Would be awesome if you could add some words about this fix to the release notes, see eclipse/xtext#1786
@miklossy Do you want me to add the details as a comment in the jira or directly to the 2020-09-01-version-2-23-0.md file?

**Comment by miklossy** [comment] 2020-08-10 14:37
Directly to the 2020-09-01-version-2.23.md file with a Pull Request

**Comment by nbhusare** [comment] 2020-08-11 09:23
@miklossy Kindly review - https://github.com/eclipse/xtext/pull/1823/files

**Comment by cdietrich** [comment] 2020-08-21 06:26
@miklossy what is the state of this issue?

**Comment by cdietrich** [comment] 2020-08-28 08:00
@miklossy @nbhusare is there anything left?

**Comment by cdietrich** [comment] 2020-08-31 06:53
i assume this fixed. if there is anything left, please create a new issue

**Closed by cdietrich** 2020-08-31 06:53 UTC
Labels: good first issue
