### ISSUE TITLE
Xtext builder stops eclipse build

### ISSUE THREAD

**Issue by stas-bob** [eclipse/xtext-eclipse#1761] opened 2021-11-17 08:12 UTC
Hello,

i have a strange behaviour of the xtext builder (Eclipse 2021-09) which i fixed but i actually dont really understand what i did. I need clarification.
When importing maven projects into workspace (xtext and not xtext natures), Xtext builder calls needRebuild() in the method pollQueuedBuildData() because JdtQueuedBuildData returns true for needsRebuild(IProject, Deltas).

First question:
JdtQueuedBuildData has a list of unconfirmedDeltas. What are these objects? What is unconfirmed about these delta objects?

Second:
the needRebuild() call sets a flag in Eclipse's BuildManager and that leads to a loop break. So following build configs are discarded. (BuildManager.basicBuild() around line 260). But because they are discarded, the list in JdtQueueBuildData had no chance to be cleared because it contains deltas of Java Files of following build configs. So, Eclipse retries the build 10 times, Xtext Builder always sets the rebuild flag and eclipse finishes building without ever building the discarded build configs. The imported projects are all broken (not built) after import.

I fixed it by overriding XtextBuilder and overrding the method pollQueuedBuildData(IProject) with empty implementation. Now Eclipse builds all projects as expected. I am totaly confused about that Xtext Builder behaviour of requesting rebuilds. Can someone explain to me what is the Issue here?

The projects have all either only maven nature or they have java+xtext+maven natures and build commands in that order.

Some projects have java build path errors because of missing source folders.

Edit1:
Also this happens only in eclipse 2021-09 because before there was that other flag in the BuildManager EARLY_EXIT_FROM_INNER_BUILD_LOOP_ALLOWED which was false by default so the build loop was not exited by break no matter if xtext builder requested rebuild or not. Now this field defaults to true. So maybe only with eclipse 2021-09 this behaviour becomes actually relevent.

**Comment by cdietrich** [comment] 2021-11-17 08:20
see also https://github.com/eclipse/xtext/issues/2404

**Comment by cdietrich** [comment] 2021-11-18 11:28
@stas-bob could you provide a set of sample maven projects you import that reproduce the problem.
@stas-bob do you see the problem also with 2.26.0.M2 (i assume yes)
@szarnekow  any idea?

**Comment by cdietrich** [comment] 2021-11-18 11:30
@szarnekow  could this also explain the RebuildAffected problems we see?
although there the behaviour is flaky

**Comment by cdietrich** [comment] 2021-11-18 11:45
could not reprodcue the 
> The imported projects are all broken (not built) after import.
thing yet

**Comment by stas-bob** [comment] 2021-11-19 11:23
i will try reproduce it with an example project. give me some time pls, i will reply in at least 7 days

**Comment by stas-bob** [comment] 2021-11-24 08:42
[xtext-issue.zip](https://github.com/eclipse/xtext-eclipse/files/7593868/xtext-issue.zip)
I attached a zip with 3 projects.
de.skeleton and de.skeleton.ui are the xtext projects which i created for this issue. it is a dsl which only contains one keyword.
The project skeleton is the runtime maven project.
How to reproduce:
1. Set max build iterations to 1-5 in workspace preferences General/Workspace/Build
2. Import the skeleton project with maven import project wizard. It will import all the 24 sub projects.
After import not all the .txt files are generated. That varies.
![xtext-issue](https://user-images.githubusercontent.com/293153/143201741-5b5825d9-2bfa-498a-bf52-f9319c2e14d7.png)
There should be 53 .txt files after import. The class SkeletonGenerator is not called.

To fix this, use -Dorg.eclipse.core.resources.disallowEarlyInnerBuildLoopExit=false Then all 53 are always generated after import.

I set max build iterations to 1-5 because the default 10 sometimes worked with this skeleton project, but 10 does reliably fail on my real project setup. Maybe because I have a lot more projects in the real setup, i dont know. Also 10 gives sometimes only 33 generated files with skeleton project.

@cdietrich

**Comment by cdietrich** [comment] 2021-11-24 08:56
@stas-bob just for curiosity: if you hit refresh on project, will then a next build round of n iterations be done?

**Comment by stas-bob** [comment] 2021-11-24 08:56
No

**Comment by cdietrich** [comment] 2021-11-24 08:57
@stas-bob no i mean: i have seen that when you do a refresh, platform will do another round of 10 projects.

**Comment by stas-bob** [comment] 2021-11-24 09:02
It does not trigger autobuild. It will trigger autobuild if i start opening files. Then out of a suddon auto build starts rebuilding. But not everything. For example i open skeleton-driving/src/main/java/Driving.java and the .txt file is generated. But other DSLs of other projects are still not there. Dont know what is going on there.

**Comment by cdietrich** [comment] 2021-11-24 09:04
will check next week. i also hope @szarnekow will find some time to look at.

**Comment by cdietrich** [comment] 2021-11-24 09:42
might also be related to the order of the builders.
normally we do

```
		<buildCommand>
			<name>org.eclipse.xtext.ui.shared.xtextBuilder</name>
			<arguments>
			</arguments>
		</buildCommand>
		<buildCommand>
			<name>org.eclipse.jdt.core.javabuilder</name>
			<arguments>
			</arguments>
		</buildCommand>
```
but in your code it seems inverse

**Comment by stas-bob** [comment] 2021-11-24 10:10
Yes because i need to load classes from java files in the same project via reflection during the xtext build.
Nevertheless, i will try to change the order and see if it makes a diffrence.

**Comment by stas-bob** [comment] 2021-11-24 11:57
No, it has no effect apparently. I just imported it once, it worked (88 files listed because txt files also in target folder etc.), deleted all projects again, imported again, now only 13 txt files listed.
![xtext-issue2](https://user-images.githubusercontent.com/293153/143234184-16c35fc9-3181-42d5-b899-3287a35675ef.png)

**Comment by cdietrich** [comment] 2021-11-24 11:59
does it happen on import only or on clean build too?!?

**Comment by stas-bob** [comment] 2021-11-24 12:01
project -> clean... clean all projects executed. Now it shows 8 txt files listed
(I have added a cleaner on eclipse clean phase which cleared generated folders where the .txt files are located. that means after i have executed clean on workspace, even less generators has been executed.

**Comment by stas-bob** [comment] 2021-11-24 12:41
Setting General/Workspace/Build max build iterations to 50 fixes it in this case. 88 files listed. Setting it to 10 builds 31 txt files.
Why does that setting even affect the build and why is xtext requesting rebuilds :D ?

**Comment by iloveeclipse** [comment] 2021-11-24 12:48
> Why does that setting even affect the build 

Hmm.. Why would `General/Workspace/Build -> max build iterations`affect the build?
Couldn't "build" setting be related to "build"? :-)

The setting is used to prevent endless build loops. 
Project A generates files in project B. Project B builds after that and generates project files in project A. Project A builds again and ...

> and why is xtext requesting rebuilds

**This** is the right question. 

Workspace tries to build projects, every time a builder requests a rebuild, new iteration starts. As long builders are requesting rebuilds & build iterations setting allows that, build continues.

**Comment by cdietrich** [comment] 2021-11-24 13:21
@iloveeclipse the counting to n is done per project or globally? i understand per project.
thus i wonder why we see jdt changes over and over and over again.

**Comment by iloveeclipse** [comment] 2021-11-24 13:25
I have to look into the code, I believe for auto-build it will be per workspace.

**Comment by cdietrich** [comment] 2021-11-24 13:32
hmmm i do not even get a needs rebuild with that set of examples if i do a clean build @stas-bob

**Comment by cdietrich** [comment] 2021-11-24 13:34
ok now i see it.
i see needsRebuild twice per project.

**Comment by stas-bob** [comment] 2021-11-24 14:13
can you reproduce what i experience ? the DSL with ending .skeleton is supposed to generate a .txt file in the project's generated folder. A lot of skeleton DSLs are not generating a txt file beause the Builder is not called during import.

**Comment by cdietrich** [comment] 2021-11-24 14:14
yes but i had to do a maven configure after import.

**Comment by stas-bob** [comment] 2021-11-24 14:18
Ok. I used the maven import wizard. No configuration was required, it also sets the generated folder as source into the .classpath because its defined in the parent pom. so the maven import itself seems fine

**Comment by cdietrich** [comment] 2021-11-30 08:54
i did some experiments and turned off all needsRebuild calls.
i used a simple dsl that generates java code.
i use this builder order

```
		<buildCommand>
			<name>org.eclipse.jdt.core.javabuilder</name>
			<arguments>
			</arguments>
		</buildCommand>
		<buildCommand>
			<name>org.eclipse.xtext.ui.shared.xtextBuilder</name>
			<arguments>
			</arguments>
		</buildCommand>
```

now when we create java files jdt wont be building the corresponding class files for that.
so it looks like for transpilers the call of needsRebuild is crucial.
thus a global limit of 10 independent of number of projects does not really make sense to me

cc @szarnekow @iloveeclipse 

i also wonder if there is another way of making changes visible to other builders

**Comment by stas-bob** [comment] 2021-11-30 09:12
> JDT wont be building the corresponding class files for that.

Why? If xtext builder creates .java files then thats a workspace change which would trigger a new autobuild?

**Comment by cdietrich** [comment] 2021-11-30 09:14
nope it looks like these files are ignored by jdt then. dont know why

**Comment by szarnekow** [comment] 2021-11-30 09:15
Workspace changes that are made by the builder during a build are not visible to a subsequent build without an invocation of `needsRebuild`
```
         * Indicates that this builder made changes that affect a build configuration that
	 * precedes this build configuration in the currently executing build order, and thus a
	 * rebuild will be necessary.
```

**Comment by cdietrich** [comment] 2021-11-30 09:18
will create a bugzilla to discuss.

**Comment by iloveeclipse** [comment] 2021-11-30 09:18
There is no new API needed, `org.eclipse.core.resources.IncrementalProjectBuilder.needRebuild()` is exactly for that.

What needed is that the code below should scale depending on the number of projects to be built:
`org.eclipse.core.internal.events.BuildManager.basicBuildLoop()

Right now it has a fixed limit for workspace, but probably it should scale that related to projects to be built?

Please also note, `org.eclipse.core.internal.events.BuildManager.buildParallel()` doesn't care at all about `rebuildRequested`  flag at all (see bug 568299 / https://git.eclipse.org/c/platform/eclipse.platform.resources.git/commit/?id=d240af240f368757546391273f196a9a6718396e).

Means, if Xtext relies on `needRebuild()` and `rebuildRequested`, it is will fail with parallel build, if I see it right.

**Comment by iloveeclipse** [comment] 2021-11-30 09:23
> nope it looks like these files are ignored by jdt then. dont know why

This is interesting and probably worth a bug for JDT. 

1. A project with Java and XYZ builder
2. XYZ builder generates a Java file in the project source path
3. If Java builder doesn't see this change, we most likely simply don't listen **during** the build on any resource events (which makes kind of sense).
4. But I wonder if resource modification events for **source** files should be noticed?
5. What about annotation processors? Do they have an extra workaround if they modify sources? Can that be generified?

**Comment by cdietrich** [comment] 2021-11-30 09:25
created https://bugs.eclipse.org/bugs/show_bug.cgi?id=577530

**Comment by stas-bob** [comment] 2021-11-30 09:26
So, you say my projects build cycle number is not high enough and thats why i end up with missing generated files after import?

**Comment by szarnekow** [comment] 2021-11-30 09:27
APT have a very controlled environment and its own notion of "rounds". These run internal to the JDT builder and are observed / implemented based on the APT SPI. I don't think this can be generalized towards multiple isolated builders on a project.

(3) The Java builder will see it if needsRebuild was called.

**Comment by cdietrich** [comment] 2021-11-30 09:27
for annotation processors i assume the notification via CompilationParticipant/BuildContext recordAddedGeneratedFiles will do the follow up build within the main build of jdt

**Comment by cdietrich** [comment] 2021-11-30 09:28
> So, you say my projects build cycle number is not high enough and thats why i end up with missing generated files after import?

no but if you set the max iterations to lets say 50 it should always work for you

**Comment by cdietrich** [comment] 2021-11-30 09:29
regarding parallel build: we dont support that anyway.

**Comment by cdietrich** [comment] 2021-11-30 09:35
i will do another experiment and write a 3rd builder and will check the deltas it sees

**Comment by cdietrich** [comment] 2021-11-30 09:46
nope, the 3rd builder running before the Xtext builder will also not see the changes by the xtext builder. so that issue is not jdt specific

**Comment by cdietrich** [comment] 2021-11-30 09:51
```
	<extension
        id="DummyBuilder"
        name="DummyBuilder"
        point="org.eclipse.core.resources.builders">
     <builder>
        <run
            class="org.xtext.example.mydsl1.ui.DummyBuilder">
        </run>
     </builder>
  </extension>
```
```
	 @Override
	    protected IProject[] build(int kind, Map<String, String> args, IProgressMonitor monitor) throws CoreException {
	        IResourceDelta delta = getDelta(getProject());
	        if (delta != null) {
	            delta.accept(new IResourceDeltaVisitor() {
	                
	                @Override
	                public boolean visit(IResourceDelta delta) throws CoreException {
	                    if (delta.getKind() == IResourceDelta.ADDED || delta.getKind() == IResourceDelta.CHANGED) {
	                        if (delta.getResource() instanceof IFile) {
	                            System.out.println(delta);
	                            // TODO file extensiion check
//	                            if (delta.getResource().getFullPath().toString().contains("/src-gen")) {
//	                                delta.getResource().touch(null);
//	                            }
	                        }
	                    }
	                    return true;
	                }
	            });
	        }
	        return null;
	    }
```
```
<?xml version="1.0" encoding="UTF-8"?>
<projectDescription>
	<name>dully</name>
	<comment></comment>
	<projects>
	</projects>
	<buildSpec>
		<buildCommand>
			<name>org.eclipse.jdt.core.javabuilder</name>
			<arguments>
			</arguments>
		</buildCommand>
		<buildCommand>
            <name>org.xtext.example.mydsl1.ui.DummyBuilder</name>
            <arguments>
            </arguments>
        </buildCommand>
		<buildCommand>
			<name>org.eclipse.xtext.ui.shared.xtextBuilder</name>
			<arguments>
			</arguments>
		</buildCommand>
	</buildSpec>
	<natures>
		<nature>org.eclipse.jdt.core.javanature</nature>
		<nature>org.eclipse.xtext.ui.shared.xtextNature</nature>
	</natures>
</projectDescription>

```

**Comment by stas-bob** [comment] 2021-11-30 12:22
> no but if you set the max iterations to lets say 50 it should always work for you

True, i tested with 100 and it works now on my original project without overriding XtextBuilder behavior in pollQueuedBuildData(IProject)

ok once again for the eclipse noobs like me:
the purpose JdtQueuedBuildData is to track new java files and request eclipse to rebuild workspace so that java builder will be active again for these new java files and everytime java builder builds a java file, it gets removed from JdtQueuedBuildData so that eventualy no rebuilds are required, but the amount of rebuilds which can be requested are limited to 10.

**Comment by cdietrich** [comment] 2021-11-30 12:41
as far as i have understood JdtQueuedBuildData/pollQueuedBuildData is needed for Xtend active annotations but i did not further reverse engineer that yet.

**Comment by stas-bob** [comment] 2021-11-30 12:46
Nevertheless, thank you for the support so far. I didnt expect that level of iteraction.

**Comment by cdietrich** [comment] 2021-12-01 12:13
@stas-bob could you also check if this patch
https://git.eclipse.org/r/c/platform/eclipse.platform.resources/+/188397
also solves the problem in your environment?

**Comment by stas-bob** [comment] 2021-12-01 12:50
I dont know how to install that patch. Can you guide me a little? do i need a p2 update site or so?

if important:
right now, i use xtext 2.25.0 in eclipse 2021-09 and in my projects I use org.eclipse.core.resources;bundle-version="3.13.500"

**Comment by cdietrich** [comment] 2021-12-01 12:55
you could go to the plug-ins view.
search core.resources there,
rightklick import as from project repository.
then change the buildmanager class manually.

or you wait 1 or 2 days until patch shows up here
https://download.eclipse.org/eclipse/updates/4.23-I-builds

**Comment by stas-bob** [comment] 2021-12-01 13:49
yes, it works now. 
I tested it with custom code in breakpoint :D it's so cool that in eclipse debug mode i can change state of objects and local variables during runtime.

**Comment by iloveeclipse** [comment] 2021-12-02 16:26
@stas-bob : please try with this SDK build that contains the patch: https://download.eclipse.org/eclipse/downloads/drops4/I20211202-0440/

**Comment by cdietrich** [comment] 2021-12-13 06:46
ping @stas-bob

**Comment by stas-bob** [comment] 2021-12-13 08:52
Sorry. Its working, i already verified the solution 12 days ago

**Comment by cdietrich** [comment] 2021-12-13 09:31
@szarnekow should we still look into the why of JdtQueuedBuildData or shall we close?

**Comment by szarnekow** [comment] 2021-12-13 13:22
pollQueuedBuildData -> Might also be related to "legacy" languages interoperating with Xbase languages. If the Xbase language needs the Java types, the rebuild is necessary after the generated Java code was compiled.

I don't remember exactly though.
For now, I'd close this one here until we see yet another issue in that area. What do you think @cdietrich ?

**Comment by cdietrich** [comment] 2021-12-13 13:27
Will close this one for now, thanks

**Closed** 2021-12-13 13:27 UTC
Labels: help_wanted, question
