### ISSUE TITLE
New project wizard breaks (permanently) if invoked by double clicking

### ISSUE THREAD

**Issue by tretum** [eclipse/xtext-eclipse#1143] opened 2019-07-18 09:02 UTC
The wizard for the new Xtext projects breaks if it is double clicked instead of using the "Next" button. This seems to permanently break the wizard even after restarts of eclipse or switching to a new workspace.

Used Eclipse version: Version: 2019-06 (4.12.0) Build id: 20190614-1200
Used Xtext version:   Xtext Complete SDK	2.18.0.v20190528-0716	org.eclipse.xtext.sdk.feature.group	Eclipse Xtext

Error message from workspace log:
```
!ENTRY org.eclipse.jface 4 2 2019-07-18 10:20:34.843
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.jface".
!STACK 0
org.eclipse.core.runtime.AssertionFailedException: null argument:
	at org.eclipse.core.runtime.Assert.isNotNull(Assert.java:88)
	at org.eclipse.core.runtime.Assert.isNotNull(Assert.java:76)
	at org.eclipse.jface.viewers.StructuredViewer.assertElementsNotNull(StructuredViewer.java:533)
	at org.eclipse.jface.viewers.StructuredViewer.getRawChildren(StructuredViewer.java:941)
	at org.eclipse.jface.viewers.StructuredViewer.getFilteredChildren(StructuredViewer.java:846)
	at org.eclipse.jface.viewers.StructuredViewer.getSortedChildren(StructuredViewer.java:1023)
	at org.eclipse.jface.viewers.AbstractListViewer.inputChanged(AbstractListViewer.java:320)
	at org.eclipse.jface.viewers.ContentViewer.setInput(ContentViewer.java:282)
	at org.eclipse.jface.viewers.StructuredViewer.setInput(StructuredViewer.java:1629)
	at org.eclipse.ui.internal.ide.dialogs.FileSystemSelectionArea.createContents(FileSystemSelectionArea.java:89)
	at org.eclipse.ui.internal.ide.dialogs.ProjectContentsLocationArea.createFileSystemSelection(ProjectContentsLocationArea.java:261)
	at org.eclipse.ui.internal.ide.dialogs.ProjectContentsLocationArea.createUserEntryArea(ProjectContentsLocationArea.java:229)
	at org.eclipse.ui.internal.ide.dialogs.ProjectContentsLocationArea.createContents(ProjectContentsLocationArea.java:167)
	at org.eclipse.ui.internal.ide.dialogs.ProjectContentsLocationArea.<init>(ProjectContentsLocationArea.java:139)
	at org.eclipse.ui.dialogs.WizardNewProjectCreationPage.createControl(WizardNewProjectCreationPage.java:126)
	at org.eclipse.xtext.xtext.ui.wizard.project.WizardNewXtextProjectCreationPage.createControl(WizardNewXtextProjectCreationPage.java:84)
	at org.eclipse.jface.wizard.WizardDialog.updateForPage(WizardDialog.java:1241)
	at org.eclipse.jface.wizard.WizardDialog.lambda$3(WizardDialog.java:1224)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:72)
	at org.eclipse.jface.wizard.WizardDialog.showPage(WizardDialog.java:1224)
	at org.eclipse.ui.internal.dialogs.NewWizardSelectionPage.advanceToNextPageOrFinish(NewWizardSelectionPage.java:73)
	at org.eclipse.ui.internal.dialogs.NewWizardNewPage.lambda$0(NewWizardNewPage.java:348)
	at org.eclipse.jface.viewers.StructuredViewer$1.run(StructuredViewer.java:776)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:47)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:176)
	at org.eclipse.jface.viewers.StructuredViewer.fireDoubleClick(StructuredViewer.java:773)
	at org.eclipse.jface.viewers.AbstractTreeViewer.handleDoubleSelect(AbstractTreeViewer.java:1516)
	at org.eclipse.jface.viewers.StructuredViewer$4.widgetDefaultSelected(StructuredViewer.java:1203)
	at org.eclipse.jface.util.OpenStrategy.fireDefaultSelectionEvent(OpenStrategy.java:251)
	at org.eclipse.jface.util.OpenStrategy.access$0(OpenStrategy.java:249)
	at org.eclipse.jface.util.OpenStrategy$1.handleEvent(OpenStrategy.java:308)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1056)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3944)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3547)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.eclipse.ui.actions.NewProjectAction.run(NewProjectAction.java:118)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:412)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1056)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3944)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3547)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:635)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1468)
```

**Comment by miklossy** [comment] 2019-07-18 11:21
@tretum Could you please upload a screencast.gif representing the issue?

**Comment by tretum** [comment] 2019-07-18 13:21
![Screencast of the issue](https://user-images.githubusercontent.com/9349315/61460429-057c3180-a96f-11e9-80ed-8cc55824d34b.gif)

**Comment by cdietrich** [comment] 2019-07-18 13:22
i wonder how you can double click the button in the first place

**Comment by tretum** [comment] 2019-07-18 15:15
I think it is expected behaviour. Every other wizard for new projects behaves as if next was pressed. I now also managed to get an installation where it does work with double click. But I managed to kill the wizard at least 3 times before

**Comment by miklossy** [comment] 2019-07-18 15:49
I have just tried this on my windows machine and it works for me. Let's see if others can reproduce this.

**Comment by cdietrich** [comment] 2019-07-18 15:50
As indicated I could neither

**Comment by cdietrich** [comment] 2019-07-19 06:12
hmmm. on my machine the guard at org.eclipse.ui.internal.ide.dialogs.ProjectContentsLocationArea.createFileSystemSelection(Composite)
exists cause i have only one file system.

@tretum do you have any hints what you do there to have multiple ones?
i also wonder if some of the ones you have work improper and return null as values within the filesystem and so this is not related to double click at all

**Comment by cdietrich** [comment] 2019-07-19 06:19
looks like this can happen with no Xtext involved too
https://bugs.eclipse.org/bugs/show_bug.cgi?id=549409

**Comment by tretum** [comment] 2019-07-19 10:39
> do you have any hints what you do there to have multiple ones?

I am not exactly sure what you mean exactly.  I have multiple partitions, but they are all NTFS, except for an apparently unassigned one.
![image](https://user-images.githubusercontent.com/9349315/61529540-dffc3000-aa21-11e9-8398-3e3c33ad29b7.png)

So this might acutally be an Eclipse bug (I cannot view the linked bug report)?
I still think it's weird that on some installations I will get the bug and on some I don't if this is related to the file system. All workspaces I have tested with are located in the same folder.

**Comment by cdietrich** [comment] 2019-07-19 10:46
you now should be able to view the bug
there is
- code that produces unwanted nulls
- a potential race condition.

you would have to remote debug that in your situation to see what happens.
with filesystem i mean: do you have any other plugins installed to eclipse.

**Comment by tretum** [comment] 2019-07-19 11:53
Ok, turns out that there probably is a plugin that is causing the issues with the broken wizard, but I previously did not see the connection.

The plugin in question is [Open Editors](https://marketplace.eclipse.org/content/open-editors) and apparently it causes these issues for quite a while, as there is an existing ticket for the plugin on Github: https://github.com/dbickley/OpenEditors/issues/19

Uninstalling the plugin always fixes the issue as far as I can see and installing it immediately causes it again.

**Comment by cdietrich** [comment] 2019-07-19 11:58
i think that plugin might cause / increase the occurrence of the the race but the fault is in eclipse itself

**Comment by tretum** [comment] 2019-07-19 12:10
Thank you for the investigation and quick replies. :)

**Comment by cdietrich** [comment] 2019-07-22 05:32
Closed as "not Xtext"

**Closed by cdietrich** 2019-07-22 05:32 UTC
Labels: help_wanted
